- name: change apt repository to jp
  replace:
    dest=/etc/apt/sources.list
    regexp="http://archive\.ubuntu\.com/"
    replace="http://jp.archive.ubuntu.com/"

- name: change timezone to Asia/Tokyo
  shell: cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

- name: apt-get update
  apt: update_cache=yes

- name: add user
  user: name={{ opsuser }} groups=sudo

- name: make .ssh directory
  file:
    path=/home/{{ opsuser }}/.ssh
    state=directory
    owner={{ opsuser }}
    mode=0700

- name: set private key
  copy:
    src=tmp/{{ opsuser }}
    dest=/home/{{ opsuser }}/.ssh/id_rsa
    owner={{ opsuser }}
    mode=0600

- name: create zone_sync directory
  file:
    path=/home/{{ opsuser }}/zone_sync state=directory
    owner={{ opsuser }}

- name: install depences
  apt: pkg={{ item }}
  with_items:
    - daemontools
